// This file has been autogenerated from a class added in the UI designer.

using System;
using System.ComponentModel;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.iOS.Views.Gestures;
using SampleApp.Portable;
using UIKit;

namespace SampleApp
{
    public partial class RegistrationCell : MvxTableViewCell, INotifyPropertyChanged
    {
        RegistartionViewModel _viewModel;
        public RegistrationCell(IntPtr handle) : base(handle)
        {
            this.DelayBind(() =>
                           {
                               var setq = this.CreateBindingSet<RegistrationCell, RegistartionViewModel>();
                               setq.Bind(NextBtn).For("TouchUpInside").To(vm => vm.Login);
                               setq.Bind().To(o => o.IsEnabled).For(p => p.IsEnabled).Mode(MvvmCross.Binding.MvxBindingMode.TwoWay);
                               setq.Apply();
                           });

        }

        public bool IsEnabled
        {
            get
            {
                NextBtn.Enabled = true;
                return NextBtn.Enabled;
            }
            set
            {
                NextBtn.Enabled = value;
                RaisePropertyChanged("IsEnabled");
            }
        }

        public string UserNameField
        {
            get
            {
                return usernameField.Text;
            }
            set
            {
                usernameField.Text = value;
                RaisePropertyChanged("UserNameField");
            }
        }


        #region INotifyPropertyChanged implementation

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void RaisePropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }
}
