// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using SampleApp.Portable;
using UIKit;

namespace SampleApp
{
    [MvxFromStoryboard(StoryboardName = "Main")]

    public partial class RegistrationViewController : MvxViewController<RegistartionViewModel>
    {
        public RegistrationViewController(IntPtr handle) : base(handle)
        {

        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            RegistrationTableSource regSource = new RegistrationTableSource(ViewModel, regtableView);

            regtableView.Source = regSource;
            var setq = this.CreateBindingSet<RegistrationViewController, RegistartionViewModel>();
            setq.Bind(submitButton).For("TouchUpInside").To(vm => vm.Login);
            setq.Apply();
        }
    }
}
